# Generated by Django 2.0.2 on 2018-03-06 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=512)),
                ('uid', models.CharField(db_index=True, max_length=128)),
                ('summary', models.CharField(max_length=512)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('nb_edits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('oldrevid', models.IntegerField(null=True)),
                ('newrevid', models.IntegerField()),
                ('oldlength', models.IntegerField()),
                ('newlength', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(max_length=256)),
                ('namespace', models.IntegerField()),
                ('uri', models.CharField(max_length=512)),
                ('comment', models.CharField(max_length=500)),
                ('parsedcomment', models.CharField(max_length=1000)),
                ('bot', models.BooleanField()),
                ('minor', models.BooleanField()),
                ('changetype', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=256)),
                ('patrolled', models.BooleanField()),
                ('reverted', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('shortid', models.CharField(max_length=32)),
                ('idregex', models.CharField(max_length=512)),
                ('idgroupid', models.IntegerField()),
                ('summaryregex', models.CharField(max_length=512)),
                ('summarygroupid', models.IntegerField()),
                ('userregex', models.CharField(max_length=512, null=True)),
                ('usergroupid', models.IntegerField(null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Tool'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('user', 'tool', 'uid')},
        ),
    ]
