# Generated by Django 2.0.3 on 2018-03-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_text_fields_instead_of_char_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('tool', 'uid', 'user')},
        ),
    ]
