# Generated by Django 2.0.3 on 2018-09-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_add_editgroups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='edit',
            name='newrevid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='edit',
            name='title',
            field=models.CharField(db_index=True, max_length=190),
        ),
    ]
