# Generated by Django 2.1 on 2018-11-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_add_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
