# Generated by Django 2.1 on 2018-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_index_edits_by_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='ended',
            field=models.DateTimeField(db_index=True),
        ),
    ]
