# Generated by Django 2.1 on 2018-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_index_batches_by_last_edit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='nb_distinct_pages',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
