# Generated by Django 2.0.3 on 2018-03-13 17:05

from django.db import migrations, models


def compute_nb_distinct_pages(apps, schema_editor):
    Batch = apps.get_model('store', 'Batch')
    for idx, batch in enumerate(Batch.objects.all().iterator()):
        if idx % 1000 == 0:
            print(idx)
        batch.nb_distinct_pages = batch.edits.all().values('title').distinct().count()
        batch.save(update_fields=['nb_distinct_pages'])

def do_nothing(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_batch_nb_distinct_pages'),
    ]

    operations = [
        migrations.RunPython(
            compute_nb_distinct_pages, do_nothing
        ),
    ]
