# Generated by Django 2.1 on 2018-12-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_recompute_nb_reverted_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total_diffsize',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
