# Generated by Django 2.1.5 on 2019-03-20 09:34

from django.db import migrations
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_recompute_stats'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='batch',
            managers=[
                ('objects', store.models.BatchManager()),
            ],
        ),
    ]
