# Generated by Django 2.1.5 on 2019-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_batch_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
