# Generated by Django 2.1.9 on 2019-09-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_batch_archived'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='edit',
            index=models.Index(fields=['batch', 'newrevid'], name='store_edit_batch_i_dc76fd_idx'),
        ),
    ]
