# Generated by Django 2.1.15 on 2021-09-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_jointly_index_batch_and_revid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='newrevid',
            field=models.IntegerField(),
        ),
    ]
