# Generated by Django 2.1.9 on 2019-09-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_jointly_index_batch_and_revid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='newrevid',
            field=models.IntegerField(),
        ),
    ]
