# Generated by Django 2.1.15 on 2023-05-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_nonempty_user_and_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='edit',
            name='newrevid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='edit',
            name='oldrevid',
            field=models.BigIntegerField(null=True),
        ),
    ]
