# Generated by Django 2.1.15 on 2021-09-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_nonempty_user_and_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='newrevid',
            field=models.IntegerField(db_index=True),
        ),
    ]
