# Generated by Django 5.1.7 on 2026-03-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reverttask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
