# Generated by Django 2.1.5 on 2019-03-20 09:26

from django.db import migrations
import tagging.models

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tagging', '0003_lexeme_tags'),
        ('store', '0016_change_batch_manager'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('objects', tagging.models.TagManager()),
            ],
        ),
    ]
