# Generated by Django 2.1.5 on 2019-03-20 09:26

from django.db import migrations
import tagging.models
from store.models import Edit
import sys

def retag_all_edits(apps, schema_editor):
    # Edit = apps.get_model('store', 'Edit')
    Tag = tagging.models.Tag

    bs = 1024
    lastpk = 0
    seen = True
    while seen:
        seen = False
        print(lastpk)
        sys.stdout.flush()
        qs = list(Edit.objects.filter(pk__gt=lastpk).order_by('pk')[:bs])
        if qs:
            Tag.retag_edits(qs)
            seen = True
            lastpk = qs[-1].pk

def do_nothing(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tagging', '0003_lexeme_tags'),
        ('store', '0016_change_batch_manager'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('objects', tagging.models.TagManager()),
            ],
        ),
        migrations.RunPython(
            retag_all_edits, do_nothing
        ),
    ]
