# Generated by Django 5.1.7 on 2026-03-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0005_inspect_batches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-priority', 'id']},
        ),
    ]
