# Run the EventStream listener on kubernetes
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: editgroups.celery.sh
  namespace: editgroups
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: editgroups.celery.sh
    spec:
      containers:
        - name: celery
          image: docker-registry.tools.wmflabs.org/toollabs-python35-base:latest
          command: [ "/data/project/editgroups/www/python/src/tasks.sh" ]
          workingDir: /data/project/editgroups/www/python/src
          env:
            - name: HOME
              value: /data/project/editgroups
          imagePullPolicy: Always
          volumeMounts:
            - name: home
              mountPath: /data/project/editgroups/
      volumes:
        - name: home
          hostPath:
            path: /data/project/editgroups/
