# Run the EventStream listener on kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: editgroups.celery.sh
  namespace: tool-editgroups
  labels:
    name: editgroups.celery.sh
    toolforge: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      name: editgroups.celery.sh
      toolforge: tool
  template:
    metadata:
      labels:
        name: editgroups.celery.sh
        toolforge: tool
    spec:
      containers:
        - name: celery
          image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
          command: [ "/data/project/editgroups/www/python/src/tasks.sh" ]
          workingDir: /data/project/editgroups/www/python/src
          env:
            - name: HOME
              value: /data/project/editgroups
          imagePullPolicy: Always
          volumeMounts:
            - name: home
              mountPath: /data/project/editgroups/
      volumes:
        - name: home
          hostPath:
            path: /data/project/editgroups/
