# Run the EventStream listener on kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: editgroups.listener.sh
  namespace: tool-editgroups
  labels:
    name: editgroups.listener.sh
    toolforge: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      name: editgroups.listener.sh
      toolforge: tool
  template:
    metadata:
      labels:
        name: editgroups.listener.sh
        toolforge: tool
    spec:
      containers:
        - name: listener
          image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
          command: [ "/data/project/editgroups/www/python/src/listener.sh" ]
          workingDir: /data/project/editgroups/www/python/src
          env:
            - name: HOME
              value: /data/project/editgroups
          imagePullPolicy: Always

